// question 1
document.getElementById("question1").innerHTML = question1
document.getElementById('q1o1').nextSibling.textContent = q1o1;
document.getElementById('q1o2').nextSibling.textContent = q1o2;
document.getElementById('q1o3').nextSibling.textContent = q1o3;
document.getElementById('q1o4').nextSibling.textContent = q1o4;
document.getElementById('q1o1').value = q1o1;
document.getElementById('q1o2').value = q1o2;
document.getElementById('q1o3').value = q1o3;
document.getElementById('q1o4').value = q1o4;

// question 2
document.getElementById("question2").innerHTML = question2
document.getElementById('q2o1').nextSibling.textContent = q2o1;
document.getElementById('q2o2').nextSibling.textContent = q2o2;
document.getElementById('q2o3').nextSibling.textContent = q2o3;
document.getElementById('q2o4').nextSibling.textContent = q2o4;
document.getElementById('q2o1').value = q2o1;
document.getElementById('q2o2').value = q2o2;
document.getElementById('q2o3').value = q2o3;
document.getElementById('q2o4').value = q2o4;

// question 3
document.getElementById("question3").innerHTML = question3
document.getElementById('q3o1').nextSibling.textContent = q3o1;
document.getElementById('q3o2').nextSibling.textContent = q3o2;
document.getElementById('q3o3').nextSibling.textContent = q3o3;
document.getElementById('q3o4').nextSibling.textContent = q3o4;
document.getElementById('q3o1').value = q3o1;
document.getElementById('q3o2').value = q3o2;
document.getElementById('q3o3').value = q3o3;
document.getElementById('q3o4').value = q3o4;

// question 4
document.getElementById("question4").innerHTML = question4
document.getElementById('q4o1').nextSibling.textContent = q4o1;
document.getElementById('q4o2').nextSibling.textContent = q4o2;
document.getElementById('q4o3').nextSibling.textContent = q4o3;
document.getElementById('q4o4').nextSibling.textContent = q4o4;
document.getElementById('q4o1').value = q4o1;
document.getElementById('q4o2').value = q4o2;
document.getElementById('q4o3').value = q4o3;
document.getElementById('q4o4').value = q4o4;

// question 5
document.getElementById("question5").innerHTML = question5
document.getElementById('q5o1').nextSibling.textContent = q5o1;
document.getElementById('q5o2').nextSibling.textContent = q5o2;
document.getElementById('q5o3').nextSibling.textContent = q5o3;
document.getElementById('q5o4').nextSibling.textContent = q5o4;
document.getElementById('q5o1').value = q5o1;
document.getElementById('q5o2').value = q5o2;
document.getElementById('q5o3').value = q5o3;
document.getElementById('q5o4').value = q5o4;

// question 6
document.getElementById("question6").innerHTML = question6
document.getElementById('q6o1').nextSibling.textContent = q6o1;
document.getElementById('q6o2').nextSibling.textContent = q6o2;
document.getElementById('q6o3').nextSibling.textContent = q6o3;
document.getElementById('q6o4').nextSibling.textContent = q6o4;
document.getElementById('q6o1').value = q6o1;
document.getElementById('q6o2').value = q6o2;
document.getElementById('q6o3').value = q6o3;
document.getElementById('q6o4').value = q6o4;

// question 7
document.getElementById("question7").innerHTML = question7
document.getElementById('q7o1').nextSibling.textContent = q7o1;
document.getElementById('q7o2').nextSibling.textContent = q7o2;
document.getElementById('q7o3').nextSibling.textContent = q7o3;
document.getElementById('q7o4').nextSibling.textContent = q7o4;
document.getElementById('q7o1').value = q7o1;
document.getElementById('q7o2').value = q7o2;
document.getElementById('q7o3').value = q7o3;
document.getElementById('q7o4').value = q7o4;

// question 8
document.getElementById("question8").innerHTML = question8
document.getElementById('q8o1').nextSibling.textContent = q8o1;
document.getElementById('q8o2').nextSibling.textContent = q8o2;
document.getElementById('q8o3').nextSibling.textContent = q8o3;
document.getElementById('q8o4').nextSibling.textContent = q8o4;
document.getElementById('q8o1').value = q8o1;
document.getElementById('q8o2').value = q8o2;
document.getElementById('q8o3').value = q8o3;
document.getElementById('q8o4').value = q8o4;

// question 9
document.getElementById("question9").innerHTML = question9
document.getElementById('q9o1').nextSibling.textContent = q9o1;
document.getElementById('q9o2').nextSibling.textContent = q9o2;
document.getElementById('q9o3').nextSibling.textContent = q9o3;
document.getElementById('q9o4').nextSibling.textContent = q9o4;
document.getElementById('q9o1').value = q9o1;
document.getElementById('q9o2').value = q9o2;
document.getElementById('q9o3').value = q9o3;
document.getElementById('q9o4').value = q9o4;

// question 10
document.getElementById("question10").innerHTML = question10
document.getElementById('q10o1').nextSibling.textContent = q10o1;
document.getElementById('q10o2').nextSibling.textContent = q10o2;
document.getElementById('q10o3').nextSibling.textContent = q10o3;
document.getElementById('q10o4').nextSibling.textContent = q10o4;
document.getElementById('q10o1').value = q10o1;
document.getElementById('q10o2').value = q10o2;
document.getElementById('q10o3').value = q10o3;
document.getElementById('q10o4').value = q10o4;

// question 11
document.getElementById("question11").innerHTML = question11
document.getElementById('q11o1').nextSibling.textContent = q11o1;
document.getElementById('q11o2').nextSibling.textContent = q11o2;
document.getElementById('q11o3').nextSibling.textContent = q11o3;
document.getElementById('q11o4').nextSibling.textContent = q11o4;
document.getElementById('q11o1').value = q11o1;
document.getElementById('q11o2').value = q11o2;
document.getElementById('q11o3').value = q11o3;
document.getElementById('q11o4').value = q11o4;

// question 12
document.getElementById("question12").innerHTML = question12
document.getElementById('q12o1').nextSibling.textContent = q12o1;
document.getElementById('q12o2').nextSibling.textContent = q12o2;
document.getElementById('q12o3').nextSibling.textContent = q12o3;
document.getElementById('q12o4').nextSibling.textContent = q12o4;
document.getElementById('q12o1').value = q12o1;
document.getElementById('q12o2').value = q12o2;
document.getElementById('q12o3').value = q12o3;
document.getElementById('q12o4').value = q12o4;

// question 13
document.getElementById("question13").innerHTML = question13
document.getElementById('q13o1').nextSibling.textContent = q13o1;
document.getElementById('q13o2').nextSibling.textContent = q13o2;
document.getElementById('q13o3').nextSibling.textContent = q13o3;
document.getElementById('q13o4').nextSibling.textContent = q13o4;
document.getElementById('q13o1').value = q13o1;
document.getElementById('q13o2').value = q13o2;
document.getElementById('q13o3').value = q13o3;
document.getElementById('q13o4').value = q13o4;

// question 14
document.getElementById("question14").innerHTML = question14
document.getElementById('q14o1').nextSibling.textContent = q14o1;
document.getElementById('q14o2').nextSibling.textContent = q14o2;
document.getElementById('q14o3').nextSibling.textContent = q14o3;
document.getElementById('q14o4').nextSibling.textContent = q14o4;
document.getElementById('q14o1').value = q14o1;
document.getElementById('q14o2').value = q14o2;
document.getElementById('q14o3').value = q14o3;
document.getElementById('q14o4').value = q14o4;

// question 15
document.getElementById("question15").innerHTML = question15
document.getElementById('q15o1').nextSibling.textContent = q15o1;
document.getElementById('q15o2').nextSibling.textContent = q15o2;
document.getElementById('q15o3').nextSibling.textContent = q15o3;
document.getElementById('q15o4').nextSibling.textContent = q15o4;
document.getElementById('q15o1').value = q15o1;
document.getElementById('q15o2').value = q15o2;
document.getElementById('q15o3').value = q15o3;
document.getElementById('q15o4').value = q15o4;

// question 16
document.getElementById("question16").innerHTML = question16
document.getElementById('q16o1').nextSibling.textContent = q16o1;
document.getElementById('q16o2').nextSibling.textContent = q16o2;
document.getElementById('q16o3').nextSibling.textContent = q16o3;
document.getElementById('q16o4').nextSibling.textContent = q16o4;
document.getElementById('q16o1').value = q16o1;
document.getElementById('q16o2').value = q16o2;
document.getElementById('q16o3').value = q16o3;
document.getElementById('q16o4').value = q16o4;

// question 17
document.getElementById("question17").innerHTML = question17
document.getElementById('q17o1').nextSibling.textContent = q17o1;
document.getElementById('q17o2').nextSibling.textContent = q17o2;
document.getElementById('q17o3').nextSibling.textContent = q17o3;
document.getElementById('q17o4').nextSibling.textContent = q17o4;
document.getElementById('q17o1').value = q17o1;
document.getElementById('q17o2').value = q17o2;
document.getElementById('q17o3').value = q17o3;
document.getElementById('q17o4').value = q17o4;

// question 18
document.getElementById("question18").innerHTML = question18
document.getElementById('q18o1').nextSibling.textContent = q18o1;
document.getElementById('q18o2').nextSibling.textContent = q18o2;
document.getElementById('q18o3').nextSibling.textContent = q18o3;
document.getElementById('q18o4').nextSibling.textContent = q18o4;
document.getElementById('q18o1').value = q18o1;
document.getElementById('q18o2').value = q18o2;
document.getElementById('q18o3').value = q18o3;
document.getElementById('q18o4').value = q18o4;

// question 19
document.getElementById("question19").innerHTML = question19
document.getElementById('q19o1').nextSibling.textContent = q19o1;
document.getElementById('q19o2').nextSibling.textContent = q19o2;
document.getElementById('q19o3').nextSibling.textContent = q19o3;
document.getElementById('q19o4').nextSibling.textContent = q19o4;
document.getElementById('q19o1').value = q19o1;
document.getElementById('q19o2').value = q19o2;
document.getElementById('q19o3').value = q19o3;
document.getElementById('q19o4').value = q19o4;

// question 20
document.getElementById("question20").innerHTML = question20
document.getElementById('q20o1').nextSibling.textContent = q20o1;
document.getElementById('q20o2').nextSibling.textContent = q20o2;
document.getElementById('q20o3').nextSibling.textContent = q20o3;
document.getElementById('q20o4').nextSibling.textContent = q20o4;
document.getElementById('q20o1').value = q20o1;
document.getElementById('q20o2').value = q20o2;
document.getElementById('q20o3').value = q20o3;
document.getElementById('q20o4').value = q20o4;